- LICENSE
to match standard found on many other GitHub Projects.
Used contents of file found in source\license.txt in source directory.
> Create LICENSE file in root

- examples/RunExampleComplexSuiteWithCustomDBMSOutputReporter.sql
- examples/ut_custom_reporter.tpb
- examples/ut_custom_reporter.tps
- source/install.sql
- source/types/ut_composite_object.tpb
- source/types/ut_composite_object.tps
- source/types/ut_suite_reporter.tpb
- source/types/ut_suite_reporter.tps
- source/types/ut_test.tpb
- source/types/ut_test.tps
- source/types/ut_test_object.tps
- source/types/ut_test_suite.tpb
- source/types/ut_test_suite.tps
Fixed custom reporter in the example after naming convention fixes
Moved Add item to the ut_composite_object type
Added object_name attribute to the ut_test_object type to save the procedure/package name for test/suite, for the suites primary to construct "suitepath" in the annotation approach
Added search procedure to find an index of the item with defined object_name in the array of ut_composite_object
Added separate setup and teardown procedures to the suite which run at the beginning of the whole suite and at the end. Currently invalidation of the all nested object is not developed
All the examples and tests do pass.
> Preparation for the annotation configuration approach and suite setup/teardown

- examples/RunAllExamples.sql
- examples/RunExampleTestAnnotationBasedForCurrentSchema.sql
- examples/test_pkg1.pck
- examples/test_pkg2.pck
- source/install.sql
- source/test_pkgs.sql
- source/test_tt.spc
- source/uninstall.sql
- source/ut_metadata.pkb
- source/ut_metadata.pks
- source/ut_suite_manager.pkb
- source/ut_suite_manager.pks
Configuration of the schema test suites based on the annotations in the schema's packages.
ut_metadata contains procedures to scan a package for pkg annotations and annotated procedures and defines necessary types.
ut_suite_manager contains procedures to process ut_metadata annotations data and configure suites hierarchies based on them.
For each package a suite is created. Also by setting %suitepackage annotation of the package like %suitepackage(parent.semiparent) one can define suites hierarchies. Suite configured for the package will be nested in the virtual suite "semiparent" which will also be nested in "parent" virtual suite.
ut_suite_manager.config_schema procedure scans for annotations all the packages in the specified schema and configure whole schema suites (several root suites …
> Configuration of the schema test suites based on the annotations

- source/ut_suite_manager.pkb
Every non UT_ package is no longer expected to have suite_tag in it
> Fixed a defect in suite_manager.

- source/types/ut_dbms_output_suite_reporter.tpb
- source/types/ut_test_object.tps
- source/ut_assert.pkb
- source/ut_assert.pks
Fixed ut_dbms_output_suite_reporter.tpb for not evaluating null assert_list object
Fixed size of object_name property as it might contain the full path with packages names
Added simple ut_assert.this as for now we have only "eq" procedure which is not enough for even simpliest appliactions
> "This" assert and minor fixes

- source/install.sql
- source/types/ut_assert_result.tpb
- source/types/ut_assert_result.tps
- source/types/ut_object.tps
- source/uninstall.sql
- source/ut_assert.pkb
- source/ut_utils.pkb
- source/ut_utils.pks
- tests/RunAll.sql
- tests/ut_assert/ut_assert.are_equal.anydata.PutsObjectStrucureIntoAssert.sql
- tests/ut_utils/ut_utils.to_string.Date.sql
- tests/ut_utils/ut_utils.to_string.Timestamp.sql
- tests/ut_utils/ut_utils.to_string.veryBigNumber.sql
- tests/ut_utils/ut_utils.to_string.verySmallNumber.sql
Removed formatting of assert message from the assertions.
Added to_string conversion functions to convert asserted to it's string representation.
Added unit tests for new utility functions.
Enriched to ut_assert_result with fields:
-expected/actual type
-expected/actual value string
-added propagation of name to the ut_assert_result (to identify assertion type)
> Now reporters can decide what and how to display from the assert

- source/ut_suite_manager.pkb
- source/ut_suite_manager.pks
This is usefull when you implement new tests and need your package to be scanned again to sence new test procedures
> Added the flag to flash cache of the parsed schema objects before run

- source/types/ut_test.tpb
- source/types/ut_test.tps
- source/types/ut_test_object.tps
- source/types/ut_test_suite.tpb
- source/types/ut_test_suite.tps
- source/ut_suite_manager.pkb
- source/ut_utils.pkb
- source/ut_utils.pks
- tests/RunAll.sql
- tests/helpers/cre_tab_ut$test_table.sql
- tests/helpers/ut_transaction_control.pck
- tests/ut_assert/ut_assert.are_equal.anydata.GivesFailureWhenComparingDifferentData.sql
- tests/ut_assert/ut_assert.are_equal.anydata.GivesSuccessWhenComparingTheSameData.sql
- tests/ut_assert/ut_assert.are_equal.anydata.PutsObjectStrucureIntoAssert.sql
- tests/ut_assert/ut_assert.is_matching.GivesFailureForMatchingString.sql
- tests/ut_assert/ut_assert.is_null.anydata.GivesFailureWhenDataIsNotNull.sql
- tests/ut_assert/ut_assert.is_null.anydata.GivesSuccessWhenDataIsNull.sql
- tests/ut_test/ut_test.Rollback_type.Auto.sql
- tests/ut_test/ut_test.Rollback_type.AutoOnFailure.sql
- tests/ut_test/ut_test.Rollback_type.Manual.sql
- tests/ut_test/ut_test.Rollback_type.ManualOnFailure.sql
- tests/ut_test_suite/ut_test_suite.Rollback_type.Auto.sql
- tests/ut_test_suite/ut_test_suite.Rollback_type.AutoOnFailure.sql
- tests/ut_test_suite/ut_test_suite.Rollback_type.Manual.sql
- tests/ut_test_suite/ut_test_suite.Rollback_type.ManualOnFailure.sql
Implemented transaction control using %rollback annotation for tests and suites. Connects to #64 
Added tests for suites and tests transaction control
Renamed department object type in anydata tests to department$ for less probable conflict with existing objects of the database if the framework is installed in non-empty schema
Fixed the error with one of existing tests
> Simple auto/manual transaction control implementation

- source/reporters/ut_teamcity_reporter.tpb
- source/reporters/ut_teamcity_reporter.tps
- source/uninstall.sql
Otherwise no outputter is defined and NULL SELF exeption is raied on use.
> Fix teamcity reporter for new outputers

- source/core/ut_suite_manager.pkb
ltrim just trims all given characters, it doesn't check patterns.
example: when specifying %suitepackages(all.logisics.xyz), the l from logistics would be trimmed as well.
> parse suitepackages bug fix.

- examples/RunAllExamples.sql
- examples/RunExampleTestAnnotationBasedForCurrentSchema.sql
- examples/RunExpectations.sql
- examples/RunWithDocumentationReporter.sql
- source/core/ut_suite_manager.pkb
- source/core/ut_suite_manager.pks
Issue #114 in a simplified form.
Now schema cache becomes invalidated when the last_ddl_time of any package in the schema change
Also corrected examples to eliminate calls to deprecated procedures:
`run_schema_suites`
`run_schema_suites_static`
`run_cur_schema_suites`
`run_cur_schema_suites_static`
> Smart schema re-parse

- source/reporters/ut_documentation_reporter.tpb
So reporter will show summary:
123 tests, 0 failures
> Now, number failures is explicitly displayed, even if it's ZERO.

- client_source/sqlplus/ut_run.sql
- docs/userguide/annotations.md
- examples/RunWithDocumentationReporter.sql
- examples/award_bonus/test_award_bonus.pkg
- examples/between_string/test_betwnstr.pkg
- examples/demo_expectations.pck
- examples/demo_of_expectations/demo_equal_matcher.sql
- examples/developer_examples/tst_pkg_huge.pks
- examples/remove_rooms_by_name/test_remove_rooms_by_name.pkg
- examples/test_pkg1.pck
- examples/test_pkg2.pck
- source/core/ut_suite_manager.pkb
- tests/helpers/test_package_1.pck
- tests/helpers/test_package_2.pck
- tests/helpers/test_package_3.pck
- tests/ut_annotations/ut_annotations.parse_package_annotations.ParseAnnotationMixedWithWrongBeforeProcedure.sql
- tests/ut_annotations/ut_annotations.parse_package_annotations.ParseAnnotationNotBeforeProcedure.sql
- tests/ut_annotations/ut_annotations.parse_package_annotations.ParseComplexPackage.sql
- tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageAndProcedureLevelAnnotations.sql
- tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageLevelAnnotation.sql
- tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageLevelAnnotationWithKeyValue.sql
- tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageLevelAnnotationWithMultilineComment.sql
Redesign according to #133 
Changin code to use new `%displayname` annotation a realized I like the old way `%suite(Name of the suite)`, `%test(Name of the test)` really much, so maybe we should get back to the old approach.
Additionaly as IDE doesn't help us with autocomplete on annotations, the less of them we need to specify, the more stable is test package configuration.
What do you think? Look at the comparison of old and new examples.
Or we can use both aproaches with `%displayname` prioritized.
> Annotations redesign

- docs/userguide/annotations.md
- readme.md
- source/core/ut_suite_manager.pkb
- tests/helpers/test_package_1.pck
- tests/ut_suite_manager/ut_suite_manager.configure_execution_by_path.PrepareRunnerForTheTopPackageByName.sql
- tests/ut_suite_manager/ut_suite_manager.configure_execution_by_path.PrepareRunnerForTheTopPackageProcedureByPath.sql
Restored old syntax as a way to define test/suite name additional to `%displayname`
If defined both `%displayname` is used
> Restored old syntax

- mkdocs.yml
Required for local documentation browsing without a web server.
Fix for Issue #170
> Change URL to be file based instead directory based.

- docs/userguide/install.md
- source/core/ut_output_buffer_tmp.sql
- source/create_utplsql_owner.sql
This is needed to be EBR ready. A user might want to test new version of the framework in another edition to not break current state. We have to support that.
> Hided output table under view to be EBR-ready

- development/readme.md
- development/releasing.md
- docs/about/CONTRIBUTING.md
- docs/about/support.md
- docs/userguide/annotations.md
- docs/userguide/best-practices.md
- docs/userguide/running-unit-tests.md
- docs/userguide/upgrade.md
- readme.md
I've made a bunch of minor updates to the markdown files based on observations from reading them for the first time.
Most of them are trivial updates, but check annotations.md in particular as was unsure about the third bullet point of section "A Suitepath can be provided in three ways".
> Minor updates to the MD documentation files

- source/core/ut_utils.pkb
- source/core/ut_utils.pks
- tests/RunAll.sql
- tests/ut_utils/ut_utils.clob_to_table_multibyte.sql
Use (3/4) * 32767 instead of 32767 as buffer default size for dbms_lob.read
> dbms_lob_read_multibyte/Fix multibyte issue with dbms_lob.read

- source/core/ut_expectation_processor.pkb
- tests/RunAll.sql
- tests/ut_expectations/ut_expectation_processor.stackOnFailedTest.sql
- tests/ut_expectations/ut_expectation_processor.stackOnUtFail.sql
Fixed stack parsing when test failed with `ut.fail`  or by broken expectation
Address #378
> Fixed stack parsing when test failed with `ut.fail` 

- source/core/types/ut_logical_suite.tpb
- source/core/types/ut_suite.tpb
- source/core/ut_suite_manager.pkb
- tests/ut_test_suite/ut_test_suite.DisabledFlagSkipSuite.sql
The `--%disabled` annotation was ignoring a suite instead of reporting all the tests from the suite as (IGNORED).
This is now resolved by:
- Propagating the disabled flag each child item (at build stage)
- Processing each child item and evaluating the disabled flag (at execute stage)
> Resolves #374

- source/create_utplsql_owner.sql
- source/install.sql
- source/install_headless.sql
This is change allows us to easily install two versions of utPLSQL v3 side by side using headless install.
We can now install develop version into `ut3_develop` and official release into `ut3` schema.
That should open doors for self-testing of utPLSQL v3 using previously released version.
> Added override user/password/tablespace for install_headless

- source/core/types/ut_expectation_result.tpb
- source/core/ut_expectation_processor.pkb
- source/core/ut_expectation_processor.pks
- tests/RunAll.sql
- tests/ut_expectation_processor/who_called_expectation.parseStackTrace.sql
- tests/ut_expectation_processor/who_called_expectation.parseStackTraceWith0x.sql
The `who_called_expectation` is now more relaxed on the stacktrace format.
Resolves #401
> Resolves issues with stacktrace not getting parsed

- source/api/ut_runner.pkb
- source/core/coverage/ut_coverage.pkb
- source/core/coverage/ut_coverage_reporter_base.tpb
- source/core/types/ut_coverage_options.tps
- source/core/types/ut_run.tpb
- source/core/types/ut_run.tps
- source/core/ut_output_buffer.pkb
- source/core/ut_suite_manager.pkb
- source/core/ut_suite_manager.pks
- source/core/ut_utils.pkb
- source/core/ut_utils.pks
- tests/RunAll.sql
- tests/ut_suite_manager/ut_suite_manager.get_schema_ut_packages.IncludesPackagesWithSutePath.sql
Resolves #368
Refactored ut_runner and ut_run, so that the ut_coverage_options are built in ut_run.
The previous implementation was confusing.
Changed data-type of send_line to avoid similar issue.
> Changed data-type used for schema_names filtering.

- .travis.yml
Moved sonar to utPLSQL organization.
Updated travis config to use sonarcloud as sonarqube is now depreciated.
> Sonar analysis is now under utPLSQL org.

- docs/userguide/coverage.md
Fixed description of coverage format (XML) for sonar. 
Added links to format documentation for coveralls and sonar.
> Fixed coverage format documentation

- source/core/ut_annotations.pkb
- source/core/ut_metadata.pkb
- tests/RunAll.sql
- tests/ut_annotations/ut_annotations.parse_package_annotations.ParseAnnotationWithWindowsNewline.sql
Had this strange behaviour today in a project where I develop on a windows machine using dbForge
> Fix problem with identifying annotations when windows newline is used

- source/reporters/ut_sonar_test_reporter.tpb
Fixed `ut_sonar_test_reporter` to map only to unit test package bodies.
> Fix to `ut_sonar_test_reporter`

- docs/userguide/running-unit-tests.md
ut_varcahr2_list => ut_varchar2_list
> fixing typo in running-unit-tests.md

- test/install_tests.sql
- test/ut_annotations/test_annotations.pkb
- test/ut_annotations/test_annotations.pks
Added test for Windows-Newline in annotations and annotations with very long names (oracle 12c allows that) to new testing approach
> Added tests from old tests to new approach

- source/api/ut_runner.pkb
- source/core/ut_dbms_output_cache.sql
- source/core/ut_utils.pkb
- source/core/ut_utils.pks
- source/install.sql
- source/uninstall.sql
- test/ut_runner/test_ut_runner.pkb
- test/ut_runner/test_ut_runner.pks
`dbms_output` buffer content is now cached before the run starts.
The outcomes from the output are spooled back to the buffer at the end of the run.
That results in the outputs getting shown in the right order when executing `ut.run` in a PLSQL block that has some buffered data already.
Resolves #482
> Added buffering of dbms_output before the run.

- source/core/annotations/ut_annotation_manager.pkb
- source/core/annotations/ut_annotation_parser.pkb
- test/ut_annotation_parser/test_annotation_parser.pkb
- test/ut_annotation_parser/test_annotation_parser.pks
- Partly resolves #516 - ORA-00001: unique constraint (UT3.UT_ANNOTATION_CACHE_PK) violated. The exception will not occur anymore, but such suite will not be executed.
- Allows for "floating" annotations
> Improvements and refactoring of `ut_annotation_parser`

- docs/userguide/install.md
Just a minor syntax fix as I noticed the windows heading not rendering correctly on the site.
> Fix MD syntax for Windows heading in install guide

- CONTRIBUTING.md
I made the change for that the guide don't say that ut3 has the last develop version, if not that It has the version of utPLSQL of your current branch in your locally repository.
Another change I made was that the last line in the "That's it" section say
this: At any time, if you need to refresh your database, the below scripts might
be helpful.
But next to that section is the "Running unit tests" section, they are not the
script that was being talked about, because they are in the secction following
"Running unit tests". So I changed the order
> Changed made to CONTRIBUTING.md

- source/core/coverage/ut_coverage.pkb
> Fixed coverage reporting for labelled `end loop` block.

- source/core/types/ut_test.tpb
- source/core/types/ut_test.tps
- source/core/ut_expectation_processor.pkb
- source/core/ut_expectation_processor.pks
- source/reporters/ut_xunit_reporter.tpb
Removed `expectations_count` as it can now be obtained from `all_expectations.count`
`ut_expectation_processor` now holds all expectation results.
`ut_test` is nor responsible for clearing the state of `ut_expectation_processor` after reading expectations results.
> Added `all_expectations` as an attribute for `ut_test` class.

- source/reporters/ut_documentation_reporter.tpb
- test/core/expectations/test_expect_not_to_be_null.pkb
- test/core/expectations/test_expect_to_be_not_null.pkb
- test/core/expectations/test_expect_to_be_null.pkb
- test/helpers/expectations_helpers.pkb
- test/helpers/expectations_helpers.pks
Aligned ut_documentation_reporter with disabled annotation
Call to this line: anydata.convertCollection(ut3.ut_expectation_processor.get_failed_expectations()) refactored to this: expectations_helpers.get_failed_expect_as_anydata()
> Aligned ut_documentation_reporter with disabled annotation

- docs/userguide/annotations.md
- source/api/ut_runner.pkb
- source/api/ut_runner.pks
- test/api/test_ut_runner.pkb
- test/api/test_ut_runner.pks
- test/install_tests.sql
- Added reporting of DIFF between cursors (rows that differ). Resolves #455
- Added new syntax to exclude elements of compound data `equal(...).excude(...)`
- Added ability to specify included elements of compound data comparison using `equal(...).include(...)` 
- Added ability to report **depreciation** of syntax for expectation. Resolves #573
- Syntax: `ut.expect(...).to_equal( ..., a_exclude => ...)` is now depreciated
- Syntax: `ut.expect(...).not_to_equal( ..., a_exclude => ...)` is now depreciated
- Syntax: `equal( ..., a_exclude => ...)` is now depreciated
- Migrated some of old tests to self-tests using utPLSQL -  #475
- Documentation now has a link to example of selecting from PLSQL record in Oracle 11g Release 2 - Resolves #554
> Added test info API to ut_runner returning pipelined table.

- .travis/install.sh
- source/api/ut_runner.pkb
- test/api/test_ut_runner.pkb
- test/api/test_ut_runner.pks
`ut_runner.run` is now performing a rollback of open transactions before finishing the run.
Resolves #601
> Fixed `ORA-02055` issue.

- .travis/install.sh
- source/api/ut.pkb
- source/api/ut_runner.pkb
- source/core/types/ut_executable.tpb
- source/core/ut_expectation_processor.pkb
- source/core/ut_expectation_processor.pks
- test/api/test_ut_run.pkb
- test/api/test_ut_run.pks
- test/install_tests.sql
All tests will now get executed even if some of them fail due to package invalidation.
Resolves #504
> State invalidation no longer stops utPLSQL from running

- source/core/types/ut_results_counter.tpb
- source/core/types/ut_results_counter.tps
- source/core/types/ut_test.tpb
- source/core/ut_expectation_processor.pkb
- source/core/ut_expectation_processor.pks
- source/core/ut_utils.pkb
- source/expectations/matchers/ut_equal.tpb
- source/expectations/ut_expectation.tpb
- source/reporters/ut_documentation_reporter.tpb
- test/core/expectations/compound_data/test_expectation_anydata.pkb
- test/core/expectations/compound_data/test_expectations_cursor.pkb
Fixed - warnings counters were not updated.
Fixed - typo in deprecation warnings
Added line number and line text to the deprecation warning.
> Deprecation warnings are now showing in `ut_documentation_reporter` output.

- docs/userguide/annotations.md
- docs/userguide/expectations.md
- docs/userguide/getting-started.md
Reworded `collection` to `nested table/varray` for schema level table-types
> Fixed misleading naming in documentation

- source/expectations/data_values/ut_compound_data_value.tpb
- source/install.sql
- source/uninstall.sql
Fixed installation order to eliminate compilation error warning
Removed ampersand symbol as some IDEs (PLSQL Developer) recognize it as a parameter to be defined
Removed unnecessary drop as ut_event_listener is already several lines before
Fixes #657
> Fixed installation order to eliminate compilation error warning

- source/core/ut_suite_builder.pkb
- test/core/reporters/test_junit_reporter.pkb
- test/core/reporters/test_junit_reporter.pks
Fixes to bug introduced in revision
Revision: c787e4793de0d89ff9770320e2e863ce25142be4
* Added support for multiple occurrences of before and after blocks.
that removed a path from ut_suite_item.tpb and move to suite_builder missing a lower case transformation for object name and procedure name.
Fixes #659
> Fixes classname not appearing when procedure name showing as mixed case, regression bug

- source/reporters/ut_junit_reporter.tpb
- source/reporters/ut_sonar_test_reporter.tpb
- source/reporters/ut_tfs_junit_reporter.tpb
- test/core/reporters/test_junit_reporter.pkb
- test/core/reporters/test_tfs_junit_reporter.pkb
Remove CDDATA and replace with xml convert
Text inside a CDDATA was not treated as xml so converting all characters was causing a poor display e.g.
```xml
Actual: &apos;test&apos; (varchar2) was expected to equal: &apos;&lt;![CDATA[some stuff]]&gt;&apos; (varchar2)
"at &quot;UT3.CHECK_FAIL_ESCAPE.FAIL_MISERABLY&quot;, line 4 ut3.ut.expect(&apos;test&apos;).to_equal(&apos;&lt;![CDATA[some stuff]]&gt;&apos;);
```
Converted all text using XML CONVERT and removing CDDATA allowed to generate proper result and escape CDDATA tags that caused failure of xml message.
```xml
Actual: 'test' (varchar2) was expected to equal: '<![CDATA[some stuff]]>' (varchar2)
"at "UT3.CHECK_FAIL_ESCAPE.FAIL_MISERABLY", line 4 ut3.ut.expect('test').to_equal('some stuff');"
```
XML content attached along with the …
> Update issue with xml special chars in failure.

- docs/userguide/annotations.md
typo originally found on http://utplsql.org/utPLSQL/latest/userguide/annotations.html. Changed documentation only. No code affected.
> fix typos in test descriptions ("tested" instead of "tesed")

- .travis.yml
- docs/userguide/advanced_data_comparison.md
- source/expectations/data_values/ut_curr_usr_compound_helper.pkb
- source/expectations/data_values/ut_curr_usr_compound_helper.pks
- source/expectations/data_values/ut_data_value_refcursor.tpb
- source/expectations/data_values/ut_data_value_refcursor.tps
- test/core/expectations/compound_data/test_expectations_cursor.pkb
- test/core/expectations/compound_data/test_expectations_cursor.pks
Fix to pk join where the key info was being collected on the collection by using convert any data object.
This was causing unwanted failure when doing normal compare.
changes been introduced to check whether the object is collection or not before invoking convert to anydata.
Because we will not drill into collections we just add information about type to  xml.
We have also added a new attribute that holds information if the cursor has a collection object type we detected. that is used to add a custom error when we are unable to match on PK. 
Unfortunately we cannot tell exactly which column refereed in join is collection  therefore to not give a false information in certain scenarios the message is very generic but is displayed after information what keys are missing.
The bug is causign a …
> Fix To Pk Join

- .travis.yml
- .travis/validate_report_files.sh
- source/reporters/ut_coverage_report_html_helper.pkb
> Update to tags in html reporter

- .travis/install.sh
- source/uninstall_all.sql
- source/uninstall_coverage_tables.sql
- source/uninstall_objects.sql
- source/uninstall_synonyms.sql
Added `uninstall_all` to remove all objects created by install.
Added calls to `uninstall_all` into deployment to validate the uninstall process completeness.
Resolves #673
> Split uninstall script into smaller, independent pieces.

- docs/userguide/annotations.md
- source/core/events/ut_event_manager.pkb
- source/core/types/ut_suite.tpb
- source/core/types/ut_suite.tps
- source/core/types/ut_suite_context.tpb
- source/core/types/ut_suite_context.tps
- source/core/types/ut_suite_item.tpb
- source/core/types/ut_suite_item.tps
- source/core/ut_suite_builder.pkb
- source/core/ut_suite_manager.pkb
- source/core/ut_suite_manager.pks
- source/core/ut_utils.pkb
- source/expectations/data_values/ut_compound_data_value.tpb
- source/expectations/data_values/ut_curr_usr_compound_helper.pkb
- source/expectations/data_values/ut_curr_usr_compound_helper.pks
- source/install.sql
- source/reporters/ut_coveralls_reporter.tpb
- source/uninstall_objects.sql
- test/core/reporters/test_coverage.pkb
- test/core/reporters/test_coverage.pks
- test/core/reporters/test_coverage/test_coveralls_reporter.pkb
- test/core/reporters/test_coverage/test_coveralls_reporter.pks
- test/core/test_suite_builder.pkb
- test/core/test_suite_manager.pkb
- test/core/test_suite_manager.pks
Changed context naming (context name can be now explicit)
Context description is now only set from `--%displayname` annotation
Resolves #679
Resolves #674
Fixed most of compiler-warnings
> Fixed running single test procedure in context by path

- mkdocs.yml
- source/reporters/ut_teamcity_reporter_helper.pkb
- test/core/reporters.pkb
- test/core/reporters/test_teamcity_reporter.pkb
- test/core/reporters/test_teamcity_reporter.pks
- the `[` and `]` were not escaped
- the `"` was escaped though not needed
- If total length of message inside the square brackets exceeds 4000 characters it's causing teamcity to report success for a test failed
Resolves #747
> Resolves issues with teamcity reporter

- .travis/install.sh
Moved uninstall testing to 12.1 - as it's now the fastest build.
Removed compiler warnings, as it's causing 60 sec delay, when installing on 11g.
> Build  speedup

- source/core/types/ut_suite_item.tpb
- test/core/test_ut_suite.pkb
- test/core/test_ut_suite.pks
Added trimming of warning when list of procedures invalidating transaction is too long.
Resolves #834
> Added trimming of warning

- source/core/annotations/ut_annotation_parser.pkb
- test/core/annotations/test_annotation_parser.pkb
- test/core/annotations/test_annotation_parser.pks
Fixed issue with `modifier => 'i'` causing strange behavior when parsing annotations on `CANADIAN FRENCH` `NLS` settings.
Resolves #844
> Fixed annotations on CANADIAN FRENCH NLS settings

- examples/developer_examples/RunExampleTestSuiteWithCompositeReporter.sql
- examples/developer_examples/RunExampleTestSuiteWithCustomReporter.sql
- source/api/ut_runner.pkb
- source/core/events/ut_event_manager.pkb
- source/core/events/ut_event_manager.pks
- source/core/output_buffers/ut_output_buffer_tmp.sql
- source/core/output_buffers/ut_output_table_buffer.tpb
- source/core/types/ut_logical_suite.tpb
- source/core/types/ut_output_reporter_base.tpb
- source/core/types/ut_output_reporter_base.tps
- source/core/types/ut_reporter_base.tpb
- source/core/types/ut_reporter_base.tps
- source/core/types/ut_run.tpb
- source/core/types/ut_suite.tpb
- source/core/types/ut_test.tpb
- source/core/ut_suite_builder.pkb
- source/core/ut_utils.pks
- test/core/reporters/test_realtime_reporter.pkb
- test/core/test_output_buffer.pkb
Default initial timeout was changed from 4 hours to 15 seconds.
All output reporters will now produce an extra leading line at the start of a test run.
Resolves #840
> `ut_output_table_buffer` will now throw an exception on timeout.

- source/core/types/ut_suite_item.tpb
- source/core/ut_savepoint_seq.sql
- source/core/ut_utils.pkb
- source/install.sql
- source/uninstall_objects.sql
- test/api/test_ut_run.pkb
Removed calls to `dbms_transaction` as they were causing library pin locks on our tests.
> Switched to use sequence for savepoint names.

- source/core/types/ut_suite_item.tps
- source/core/ut_suite_cache.sql
- source/core/ut_suite_manager.pkb
- source/core/ut_utils.pkb
- source/core/ut_utils.pks
- test/core/test_suite_manager.pkb
- test/core/test_suite_manager.pks
This will iterate over all objects and report back any object that tries to insert an suitepath over 1k character.
Fixes  #848
> Modify a code to fail when inserting a suitepath over 1k long.

- source/expectations/data_values/ut_compound_data_helper.pkb
- source/expectations/data_values/ut_compound_data_helper.pks
- source/expectations/data_values/ut_data_value_refcursor.tpb
- test/core/min_grant_user/test_min_grant_user.pkb
- test/core/min_grant_user/test_min_grant_user.pks
- test/helpers/ut3user#.test_cursor_grants.pkb
- test/helpers/ut3user#.test_cursor_grants.pks
Fixes #870
Fixing issue when cursor was opened with privs of the user instead of framework when accessing internal function.
> Moving a compare SQL into helper function to avoid privs issue

- source/core/output_buffers/ut_message_id_seq.sql
- source/core/output_buffers/ut_output_buffer_base.tps
- source/core/output_buffers/ut_output_buffer_tmp.sql
- source/core/output_buffers/ut_output_table_buffer.tpb
- source/core/output_buffers/ut_output_table_buffer.tps
- source/install.sql
- source/uninstall_objects.sql
Changed how delete from output buffer table is handled - use ROWID.
Increased fetch size from 100 to 3000 rows for output buffer.
Resolves #882
> Fixed storage for `clob` in output buffer table - make it inline.

- source/expectations/data_values/ut_compound_data_helper.pkb
- test/ut3_user/expectations/test_expectations_cursor.pkb
- test/ut3_user/expectations/test_expectations_cursor.pks
fixing "ORA-00907: missing right parenthesis" when comparing ref cursors with BINARY_DOUBLE/BINARY_FLOAT columns, because these column types do not support type length
Stack trace:
1) ut_get_data
ORA-00907: missing right parenthesis
ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 318
ORA-06512: at "UT3.UT_COMPOUND_DATA_HELPER", line 596
ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 309
ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 366
ORA-06512: at "UT3.UT_EQUAL", line 225
ORA-06512: at "UT3.UT_EXPECTATION", line 26
ORA-06512: at "UT3.UT_EXPECTATION", line 138
ORA-06512: at "TDS2.UT_TDSPATANSINTPKG", line 117
ORA-06512: at "TDS2.UT_TDSPATANSINTPKG", line 117
ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 318
ORA-06512: at "UT3.UT_COMPOUND_DATA_HELPER", line 596
ORA-06512: at …
> fix/ORA-00907 when comparing ref cursors with BINARY_... columns

- source/expectations/data_values/ut_compound_data_helper.pkb
- source/expectations/data_values/ut_cursor_column.tpb
- source/expectations/data_values/ut_cursor_column.tps
- source/expectations/data_values/ut_cursor_details.tpb
- test/ut3_user/expectations/test_expectations_cursor.pkb
- test/ut3_user/expectations/test_expectations_cursor.pks
Fixes #907 
Number precision was incorrect when using max_col_len for data from dual.
This was changed to used a simple number with no precision.
> Number precision from dbms_sql not correct

- source/core/output_buffers/ut_output_clob_table_buffer.tpb
- source/core/output_buffers/ut_output_table_buffer.tpb
- test/ut3_tester/core/test_output_buffer.pkb
- test/ut3_tester/core/test_output_buffer.pks
We have gaps in message_id of output_buffers if line are reported using bulk procedure with null `text` value. Small fix eliminate such gaps and improves queries on output_buffers as they are limited by message_id range.
> Fix message id in output buffer

- source/reporters/ut_coverage_cobertura_reporter.tpb
- test/install_and_run_tests.sh
- test/ut3_user/reporters/test_coverage/test_cov_cobertura_reporter.pkb
- test/ut3_user/reporters/test_coverage/test_cov_cobertura_reporter.pks
Fixed issue with missing newlines in cobertura coverage for non-executed packages.
Resolves #917
> Fixed issue with missing newlines in cobertura coverage

- source/core/annotations/ut_annotation_manager.pkb
- source/core/coverage/ut_coverage.pkb
- source/core/types/ut_suite_item.tpb
- source/core/ut_metadata.pkb
- source/core/ut_suite_manager.pkb
Used dbms_assert.qualified_sql_name whenever possible.
This is much less invasive than dbms_assert.enquote_name.
Code converting case is left untouched.
> Fixes #921 - Assert input params in dynamic SQL

- source/core/types/ut_executable.tpb
- source/core/types/ut_executable.tps
- source/core/ut_metadata.pkb
- source/core/ut_metadata.pks
- test/ut3_tester/core/annotations/test_before_after_annotations.pkb
- test/ut3_user/api/test_ut_run.pkb
- test/ut3_user/api/test_ut_run.pks
Fixed issue with utPLSQL failing to run when schema contains package named the same as schema owning it.
It is now possible to have utPLSQL test package like this:
```
create or replace package some_schema.some_schema as
--%suite
--%test
procedure sample_test;
end;
/
create or replace package body some_schema.some_schema as
procedure sample_test is begin ut.expect(1).to_equal(1); end;
end;
/
```
The tests from the package can be invoked by calling:
`exec ut.run('some_schema.some_schema');`
If only schema is provided, all test packages in schema are executed.
`exec ut.run('some_schema');`
Resolves #569
Resolves #885
> Removed dependency on `dbms_utility.name_resolve`.

- source/core/annotations/ut_annotation_manager.pkb
- source/core/ut_utils.pkb
- test/ut3_tester/core/annotations/test_annotation_manager.pkb
Resolves problem when sources are passed via JDBC or dynamic SQL for compilation and source code contains leading comments.
The code was adjusted to properly read sources even when they are getting passed with leading comments containing create package statement.
Now, the following will be properly parsed:
```sql
begin
execute immediate q'[
/*
* Some multiline comments before package spec
create or replace package dummy_test_package dummy comment to prove that we pick the right piece of code
*/
-- create or replace package dummy_test_package dummy comment to prove that we pick the right piece of code
--Some single-line comment before package spec
create or replace package dummy_test_package as
--%suite(dummy_test_suite)
--%rollback(manual)
--create or replace package dummy_test_package …
```
> Fixed issue with parsing via trigger source with leading comments

- .travis/install.sh
- source/uninstall_objects.sql
- test/ut3_user/expectations/test_expectations_cursor.pkb
- test/ut3_user/expectations/test_expectations_cursor.pks
Resolves: #952
Added safety check on drop of optional objects.
Added safety harness to fail build if any of uninstall steps raises exceptions.
> Added test to confirm that long column names are suported in 3.1.7

- source/reporters/ut_realtime_reporter.tpb
This makes warnings and error more readable without changing the underlying model.
removed also tailing spaces on some code lines
> fixes #961 - separate warnings and errors with two linefeeds

- .gitignore
Avoid deleting this file after each full test run. 
Ignoring this file is simpler.
> ignore cobertura.xml which is created by a test run

- source/check_sys_grants.sql
This commit fixes an issue in the installation when the CREATE ANY CONTEXT right is granted instead of CREATE CONTEXT.
> Fix check of sys grants with ANY (issue #992)

- docs/userguide/install.md
Parameter name should be `a_object_owner`.
See [package specification](https://github.com/utPLSQL/utPLSQL/blob/48b9d2e1d8cce7cce714bb6b0d1816788c4eb3a8/source/api/ut_runner.pks#L85).
> Corrected rebuild_annotation_cache parameter in the Install Guide

- source/expectations/data_values/ut_compound_data_helper.pkb
- test/ut3_user/expectations/test_expectations_cursor.pkb
- test/ut3_user/expectations/test_expectations_cursor.pks
Columns:
- ITEM_DATA
- DATA_ID
- ITEM_NO
- DUP_NO
- POSITION
Can now be safely used in cursors.
Resolves #997
Added delete on DIFF temp tables after cursor / object compare.
Resolves #998
> Changed names on internal columns in cursor & object compare.

- source/core/types/ut_executable_test.tpb
- source/core/types/ut_executable_test.tps
- source/core/types/ut_suite_cache_row.tps
- source/core/types/ut_suite_item.tpb
- source/core/types/ut_suite_item.tps
- source/core/types/ut_test.tpb
- source/core/types/ut_test.tps
- source/core/ut_suite_builder.pkb
- source/core/ut_suite_cache_manager.pkb
- test/ut3_tester/core/annotations/test_annot_throws_exception.pkb
- test/ut3_tester/core/annotations/test_annot_throws_exception.pks
- test/ut3_tester/core/test_suite_builder.pkb
- test/ut3_tester/core/test_suite_builder.pks
Now the validation is executed at runtime, when the tests is executed.
This resolves issues related to the fact that some package constants may not exist or be valid at suite parse time.
In such scenario, the annotations continued to be ignored despite the fact that package constants were valid at test runtime.
With this change, tests can now have `--throws` annotations referencing constants that are undefined at compile time.
Resolves #1033
Resolves #721
> Moved validation of `--%throws` annotation values.

- .travis/install.sh
- source/check_sys_grants.sql
- source/core/annotations/ut_annotation_manager.pkb
- source/core/ut_metadata.pkb
- source/core/ut_suite_manager.pkb
- test/ut3_tester/core/annotations/test_annotation_cache.pkb
- test/ut3_tester/core/annotations/test_annotation_cache.pks
- test/ut3_tester_helper/annotation_cache_helper.pkb
Resolves #1050 
Related to #1051
> Improvements to privilege handling in utPLSQL

- source/core/coverage/dbms_plssqlcode.sql
This is prerequisite for multi-session coverage.
Also it's needed for our self-testing to run properly.
> Changed `dbms_plssqlcode` tables to be permanent.

- source/core/ut_utils.pkb
- source/reporters/ut_realtime_reporter.tpb
- test/ut3_user/reporters/test_junit_reporter.pkb
> Fixed CDATA tagging in JUnit reporter

- source/reporters/ut_coverage_cobertura_reporter.tpb
#1107
The missing <classes> tags cause several CICD tools fail when displaying test coverage
> Added missing <classes> tag

- source/reporters/ut_coverage_cobertura_reporter.tpb
- test/ut3_user/reporters/test_coverage/test_cov_cobertura_reporter.pkb
- test/ut3_user/reporters/test_coverage/test_coverage_standalone.pkb
- test/ut3_user/reporters/test_coverage/test_proftab_coverage.pkb
with covered lines / total  total lines.
Rounding to 17 decimal places since that's what I found when looking at cobertura examples online.
Used an rpad to generate the format mask to avoid having a long string of 9s.
This was mentioned in #1107 but does not have an issue of its own.
> Replaced hard coded 0 in total test coverage

- docs/userguide/expectations.md
This should be less problematic than #1171, I mostly fix obvious typos.
I believe the new note on negating `to_contain` is in place, as it may be rather surprising that `not_to_contain` is not a negation of `to_contain`.
> Minor typo, style and grammar fixes

- docs/about/project-details.md
- docs/about/support.md
- readme.md
I used the link from the ![obraz](https://user-images.githubusercontent.com/53443372/148128014-80a58484-5217-4006-bf81-b6962c717495.png) badge in `readme.md`. The replaced link is no longer active.
> Replace inactive Slack invitation link

- source/core/annotations/ut_annotation_cache_manager.pkb
- test/ut3_tester/core/test_suite_manager.pkb
- test/ut3_tester/core/test_suite_manager.pks
Closing #1177 
This is to address situation when a package is created with tests and then subsequently replaced by another version where annotations are removed.
> Adding option to remove a cache for annotations on existing packag

- source/core/coverage/ut_coverage_helper_block.pkb
- source/core/ut_utils.pkb
- test/ut3_tester_helper/coverage_helper.pkb
- test/ut3_tester_helper/coverage_helper.pks
- test/ut3_user/reporters/test_coverage/test_extended_coverage.pkb
- test/ut3_user/reporters/test_coverage/test_extended_coverage.pks
Implemented a workaround that allows for running utPLSQL tests with code coverage on source with calls to DBMS_STATS.
Resolves: #1097
Resolves: #1094
> Gather coverage on code calling DBMS_STATS.

- source/core/coverage/ut_coverage.pkb
> Improved get_cov_sources SQL query.

- source/reporters/ut_realtime_reporter.tpb
- test/ut3_user/reporters/test_realtime_reporter.pkb
- test/ut3_user/reporters/test_realtime_reporter.pks
The `ut_realtime_reporter` used by utPLSQL-SQL-Developer-extension and utPLSQL-PLSQL-Developer-plugin  is now capable of providing reason for a disabled test.
The reason is provided as a tag `<disabledReason>reason</disabledReason>` in the `pre-run` event, describing the suites before run is started.
If no reason is provided, the tag is not present in the output.
Resolves: #1192
> Added disabledReason to `ut_realtime_reporter`

- docs/userguide/annotations.md
- source/core/session_context/ut_session_info.tpb
- test/ut3_user/api/test_ut_run.pkb
This will allow for more accurate coverage reporting when running tests against the coverage module of the framework.
With this, in the test, we can get the current `coverage_run_id` and pass it to the JOB that runs utPLSQL in separate session.
After the JOB is finished, we can then copy the output from `ut3_develop` coverage tables into `ut3` coverage tables.
That way, we will get a full picture of the coverage gathered in the course of utPLSQL test-run with coverage enabled.
Most of the setup is already in place in our tests. The only missing peace was the ability to tie the current `ut3` test-run with the coverage gathered by jobs.
So now, after each test JOB, we can copy the coverage over to `ut3`.
I suggest using negative-id's when performing the copy from `ut3_develop` …
> Add COVERAGE_RUN_ID to utPLSQL context 

- docs/userguide/annotations.md
- docs/userguide/expectations.md
Fix typos in documentation.
-  annotations.md
-  `be` instead of `by` 
- expectations.md
-  `whether` instead of `wheter`
Found out during update of snippets provided by the SQLDev extension.
> fix typo, "can be provided" instead of "can by provided" in annotations.md

- docs/userguide/reporters.md
Custom reporters are mentioned in a few places in the docs. Also, `README.md` lists "plugin architecture for reporters and matchers" as one of the key features. But there is no section in the docs that actually describes how to add a custom reporter. I believe that this short description of the process may be useful (it would be useful for me).
Sorry - I didn't have time to build the website  and check if it looks ok, but I don't see why it wouldn't.   (I've had a revolution in my family life in the last few months, and now I hardly have time for anything)
I decided not to describe the necessary grants when the custom reporter is created outside of the `UT3` schema. I state that this is not recommended, If someone wants to follow this path, let them do it at their own risk. Also, I'm not …
> Add a section on custom reporters.

- source/create_utplsql_owner.sql
The privileges on the referenced packages are often revoked from PUBLIC as database hardening. Not relying on these grants being available makes the install script more robust.
See also issue #1229
> Add explicit grants for public packages

- source/reporters/ut_coverage_report_html_helper.pkb
- test/ut3_user/reporters/test_coverage/test_html_coverage_reporter.pkb
- test/ut3_user/reporters/test_coverage/test_html_coverage_reporter.pks
Sourcecode lines that result in more than 4000 chars after conversion to HTML should be reported successfully.
Resolves: #1232
> Ability to report coverage on long lines.

- development/refresh_sources.sh
- docs/userguide/install.md
- examples/developer_examples/RunExampleTestSuiteWithCompositeReporter.sql
- source/core/coverage/ut_coverage_reporter_base.tpb
- source/core/output_buffers/ut_output_buffer_base.tpb
- source/core/output_buffers/ut_output_buffer_base.tps
- source/core/output_buffers/ut_output_clob_table_buffer.tpb
- source/core/output_buffers/ut_output_clob_table_buffer.tps
- source/core/output_buffers/ut_output_table_buffer.tpb
- source/core/output_buffers/ut_output_table_buffer.tps
- source/core/types/ut_output_reporter_base.tpb
- source/core/types/ut_output_reporter_base.tps
- source/create_utplsql_owner.sql
- test/ut3_tester/core/test_output_buffer.pkb
- test/ut3_tester/core/test_output_buffer.pks
- test/ut3_tester_helper/coverage_helper.pkb
Resolves #1242
Refactored output buffers to have better segregation of responsibilities.
Changed behavior of output buffers `get_lines` procedure to stop immediately after consuming all produced data if producer has stopped. 
Changed behavior of output buffers `get_lines` procedure not to timeout after 4 hours, if producer is still running.
> Allow for test runs over 4 hours

- source/expectations/matchers/ut_contain.tpb
- source/expectations/ut_expectation.tpb
- test/ut3_user/expectations/test_expectation_anydata.pkb
- test/ut3_user/expectations/test_expectation_anydata.pks
- test/ut3_user/expectations/test_expectations_cursor.pkb
- test/ut3_user/expectations/test_expectations_cursor.pks
Address issue where the not_to(contain) executes a negated matcher wi…thout negated flag set causing refcursor compare sql generated inclusion comparision.
fixes #1245
> Address issue where the not_to(contain) not run correctly

- source/core/annotations/ut_annotation_manager.pkb
- source/core/annotations/ut_annotation_parser.pkb
- source/core/types/ut_executable_test.tpb
- source/core/ut_expectation_processor.pkb
- source/core/ut_metadata.pkb
- source/core/ut_suite_cache_manager.pkb
- source/core/ut_suite_manager.pkb
- source/core/ut_utils.pkb
- test/ut3_tester/core/test_suite_manager.pkb
- test/ut3_tester/core/test_suite_manager.pks
Resolves #1252
Replaced all regexp ranges with posix representations to avoid NLS_SORT impact on regex behavior.
> Fix regex to be NLS_SORT independent

- source/core/output_buffers/ut_output_buffer_base.tpb
- source/core/output_buffers/ut_output_buffer_base.tps
- source/core/output_buffers/ut_output_buffer_tmp.sql
- source/core/output_buffers/ut_output_bulk_buffer.tpb
- source/core/output_buffers/ut_output_clob_buffer_tmp.sql
- source/core/output_buffers/ut_output_clob_table_buffer.tpb
- source/core/output_buffers/ut_output_table_buffer.tpb
- source/core/ut_utils.pkb
- source/core/ut_utils.pks
- source/uninstall_objects.sql
- test/ut3_tester/core/test_output_buffer.pkb
- test/ut3_tester/core/test_output_buffer.pks
- test/ut3_tester/core/test_ut_utils.pkb
- test/ut3_tester/core/test_ut_utils.pks
When dealing with multibyte strings, the substring limit of 4000 **chars** is not correct. We need to apply a limit of 4000 **bytes** to both VARCHAR2 and to CLOB data types. This means we need to have a function to calculate lenght of CLOB in bytes. This is now added and all the conversions/trimming/string-splitting is done using the string length in **bytes**
Additionally, a different approach (with sequences) was introduced into output buffers to avoid the sometime occurring PK violation on the output buffer tables. The new approach may add a but overhead on reading from / saving into buffer, but will definitely address the threat of PK errors.
Resolves #1254
Resolves #1128
> Fix output length error and output buffer.

- source/reporters/ut_coverage_cobertura_reporter.tpb
- test/ut3_user/reporters/test_coverage/test_cov_cobertura_reporter.pkb
- test/ut3_user/reporters/test_coverage/test_coverage_standalone.pkb
Fixes #1268
Currently the cobertura coverage reported set the line-rate for class and packages to 0. This seems to have impact on some of new versions of publish reporters.
> The line-rate is not recorded for packages and classes in cobertura coverage reporter

- source/reporters/ut_tfs_junit_reporter.tpb
- test/ut3_user/reporters/test_tfs_junit_reporter.pkb
- test/ut3_user/reporters/test_tfs_junit_reporter.pks
Fixes #1081 
Fixes #1257
As per notes on 1081 the new code will roll up context into suites.
And report empty test suites only when number of tests is equal 0.
> Update TFS reporter to correct format
