utPLSQL/utPLSQL

CONTRIBUTING.md

Created a CONTRIBUTING.md file that describes the basics of out to use GIT and GITHUB
and good practices on contributing to projects.

Created a CONTRIBUTING.md  File

---

documentation/src/admin.html
documentation/src/index.html
documentation/src/writedoc.html

This only changes the files in the documenation/src folder 
It's to help with issue #4 
(Connected to #4)

Initial changes to get the docs/website to refer to github

---

source/types/ut_composite_reporter.tpb

The reporter was missing assignment in the constructor.

Composite reporter is now working as expected.

---

source/install.sql
source/ut_suite_manager.pkb

Syntax Bug fix and changes to install.sql to help catch problem.

Syntax Bug Fix

---

examples/RunAllExamples.sql
examples/RunExampleTestAnnotationsHugePackage.sql
examples/test_pkg1.pck
examples/tst_pkg_huge.pks
source/ut_metadata.pkb
source/ut_suite_manager.pkb
source/ut_suite_manager.pks

- added some comments
- switched to $$ut_trace compilation flag
- refactored config_package procedure specification
- added huge package for parsing tests
- added example of parsing huge package spec
- switched to all_source/dba_source views depending on current grants
- redefined objects exclusion list for config_schema procedure

Annotation parser performance improvements

---

.gitmodules
.travis/create_utplsql_user.sql
CONTRIBUTING.md
source/ut_assert.pkb
source/ut_assert.pks
tests/RunAll.sql
tests/ut_assert/common/ut_assert.null.scalar.common.sql
tests/ut_assert/ut_assert.are_equal.anydata.PutsObjectStrucureIntoAssert.sql
tests/ut_assert/ut_assert.is_not_null.date.GivesFailureForNullValue.sql
tests/ut_assert/ut_assert.is_not_null.date.GivesSuccessForNotNullValue.sql
tests/ut_assert/ut_assert.is_null.anydata.GivesFailureWhenDataIsNotNull.sql
tests/ut_assert/ut_assert.is_null.anydata.GivesSuccessWhenDataIsNull.sql
tests/ut_assert/ut_assert.is_null.date.GivesFailureForNotNullValue.sql
tests/ut_assert/ut_assert.is_null.date.GivesSuccessForNullValue.sql

Added grants for dbms_crypto (required by any_data MD5 calculation).
Added is_null and is_not_null assertions.
Updated test for any_data to_string outcomes.
Updated CONTRIBUTING.md to include instruction for submodule update.

Updated submodule to point to master repo for any_data.

---

examples/RunExampleTestAnnotationsHugePackage.sql
source/install.sql
source/uninstall.sql
source/ut_annotations.pkb
source/ut_annotations.pks
source/ut_metadata.pkb
source/ut_metadata.pks
source/ut_suite_manager.pkb
source/ut_suite_manager.pks
tests/RunAll.sql
tests/helpers/check_annotation_parsing.prc
tests/ut_annotations/ut_annotations.parse_package_annotations.ParseAnnotationMixedWithWrongBeforeProcedure.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParseAnnotationNotBeforeProcedure.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParseComplexPackage.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageAndProcedureLevelAnnotations.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageLevelAnnotation.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageLevelAnnotationWithKeyValue.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageLevelAnnotationWithMultilineComment.sql

Now annotations are separated from DB metadata processing.

Cleanup and separation of annotation processing.

---

.travis/oracle/download.js
.travis/oracle/install.sh

the previosu merge of /cbandy/travis-oracle/pull/17 for travis-oracle
missed/removed some functionailty relating to login credentials.

remerge of travis-oracle patch

---

source/install.sql
source/types/ut_composite_object.tpb
source/types/ut_test.tpb
source/types/ut_test.tps
source/types/ut_test_object.tpb
source/types/ut_test_object.tps
source/types/ut_test_suite.tpb
source/types/ut_test_suite.tps
source/ut_suite_manager.pkb
source/ut_utils.pkb
source/ut_utils.pks
tests/RunAll.sql
tests/helpers/cre_tab_ut$test_table.sql
tests/helpers/ut_transaction_control.pck
tests/ut_assert/ut_assert.are_equal.anydata.GivesFailureWhenComparingDifferentData.sql
tests/ut_assert/ut_assert.are_equal.anydata.GivesSuccessWhenComparingTheSameData.sql
tests/ut_assert/ut_assert.are_equal.anydata.PutsObjectStrucureIntoAssert.sql
tests/ut_assert/ut_assert.is_matching.GivesFailureForMatchingString.sql
tests/ut_assert/ut_assert.is_null.anydata.GivesFailureWhenDataIsNotNull.sql
tests/ut_assert/ut_assert.is_null.anydata.GivesSuccessWhenDataIsNull.sql
tests/ut_test/ut_test.IgnoreFlagSkipTest.sql
tests/ut_test/ut_test.Rollback_type.Auto.sql
tests/ut_test/ut_test.Rollback_type.AutoOnFailure.sql
tests/ut_test/ut_test.Rollback_type.Manual.sql
tests/ut_test/ut_test.Rollback_type.ManualOnFailure.sql
tests/ut_test_suite/ut_test_suite.IgnoreFlagSkipSuite.sql
tests/ut_test_suite/ut_test_suite.Rollback_type.Auto.sql
tests/ut_test_suite/ut_test_suite.Rollback_type.AutoOnFailure.sql
tests/ut_test_suite/ut_test_suite.Rollback_type.Manual.sql
tests/ut_test_suite/ut_test_suite.Rollback_type.ManualOnFailure.sql

Added ignore annotation to bypass tests and suites
This PR has only 1 commit after #71

"Ignore" annotation

---

readme.md

Update the readme to include status shields and an initial comparison of v2 to v3 features.
To see the changes rendered...  Click on "Files changed", and then "View" on the file.

Overview, v2 to v3,  Status Shields

---

.gitattributes
.travis/install.sh
build/utplsql_style_check.sql
source/install.sql

added a script to do a  simple naming style check.
can be enhanced in future with additional checks
or to cause failure on failure

Feature: simple naming rule checks

---

source/expectations/matchers/be_between.tpb
source/expectations/matchers/be_between.tps
source/expectations/ut_expectation.tps
source/expectations/ut_expectation_date.tpb
source/expectations/ut_expectation_date.tps
source/expectations/ut_expectation_number.tpb
source/expectations/ut_expectation_number.tps
source/expectations/ut_expectation_timestamp.tpb
source/expectations/ut_expectation_timestamp.tps
source/expectations/ut_expectation_timestamp_ltz.tpb
source/expectations/ut_expectation_timestamp_ltz.tps
source/expectations/ut_expectation_timestamp_tz.tpb
source/expectations/ut_expectation_timestamp_tz.tps
source/expectations/ut_expectation_varchar2.tpb
source/expectations/ut_expectation_varchar2.tps
source/install.sql
source/uninstall.sql
tests/RunAll.sql
tests/asssertions/common/ut.expect.to_be_between.scalar.common.sql
tests/asssertions/common/ut.expect.to_be_between.scalar.different_types.common.sql
tests/asssertions/common/ut.expect.to_be_between.scalar.with_message.common.sql
tests/asssertions/ut.expect.to_be_between.GivesFailureForDifferentValues.sql
tests/asssertions/ut.expect.to_be_between.GivesFailureWhenActualIsNull.sql
tests/asssertions/ut.expect.to_be_between.GivesFailureWhenBothActualAndExpectedRangeIsNull.sql
tests/asssertions/ut.expect.to_be_between.GivesFailureWhenExpectedRangeIsNull.sql
tests/asssertions/ut.expect.to_be_between.GivesSuccessWhenDifferentTypes.sql
tests/asssertions/ut.expect.to_be_between.GivesTrueForCorrectValues.sql
tests/asssertions/ut.expect.to_be_between.with_text.GivesTheProvidedTextAsMessage.sql

Be_between matcher implementation.
Tests are included.
On review please pay attention to the null processing, not sure I've implemented it correctly as designed. What if expected value is null, what if actual is null.

Be_between matcher

---

source/core/types/ut_test_suite.tpb

don't know how to make a nice test
#121

fixed the bug

---

source/core/ut_suite_manager.pkb

fixed cache invalidation comporator

---

source/core/annotations/ut_annotations.pkb
source/core/annotations/ut_annotations.pks
source/core/ut_suite_manager.pkb
tests/helpers/check_annotation_parsing.prc
tests/ut_annotations/ut_annotations.parse_package_annotations.ParseAnnotationMixedWithWrongBeforeProcedure.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParseComplexPackage.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageAndProcedureLevelAnnotations.sql

Shuffled execution will be implemented later

Sorted tests in suites in the order they appear in package

---

source/core/ut_suite_manager.pkb

Made test inherit suites rollback

Bug: test doesn't inherit suite's rollback

---

source/core/annotations/ut_annotations.pkb
tests/RunAll.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageLevelAnnotationAccessibleBy.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParsePackageLevelAnnotationMultilineDeclare.sql

fixed multiline annotations parsingv
added accessible by clause to package parsing

fix multiline annotations parsing and accessible by

---

source/core/types/ut_assert_result.tpb
source/expectations/matchers/ut_be_between.tpb
source/expectations/matchers/ut_be_false.tpb
source/expectations/matchers/ut_be_greater_or_equal.tpb
source/expectations/matchers/ut_be_greater_than.tpb
source/expectations/matchers/ut_be_less_or_equal.tpb
source/expectations/matchers/ut_be_less_than.tpb
source/expectations/matchers/ut_be_like.tpb
source/expectations/matchers/ut_be_not_null.tpb
source/expectations/matchers/ut_be_null.tpb
source/expectations/matchers/ut_be_true.tpb
source/expectations/matchers/ut_equal.tpb
source/expectations/matchers/ut_match.tpb

address #160

---

.travis/create_release_archive.sh

Add client_source directory to archive.

---

docs/userguide/annotations.md
examples/between_string/test_betwnstr.pkg
source/core/ut_suite_manager.pkb
tests/helpers/test_package_3.pck
tests/ut_suite_manager/ut_suite_manager.configure_execution_by_path.PrepareRunnerForTheSchema.sql
tests/ut_suite_manager/ut_suite_manager.configure_execution_by_path.PrepareRunnerForTheTopPackageWithoutSubsuitesByName.sql
tests/ut_suite_manager/ut_suite_manager.configure_execution_by_path.PrepareRunnerForTheTopPackageWithoutSubsuitesByPath.sql

Renamed `disable` annotation to `disabled`

renamed "disable" annotation to "disabled"

---

source/core/types/ut_event_listener.tpb

Fixed typo

---

source/reporters/ut_documentation_reporter.tpb

fix documentation_reporter generating empty lines

---

client_source/sqlplus/ut_run.sql

ut_run.sql will now:
- fail with exception if invalid reporter name was passed
- run the background process as minimized command window (on windows OS).

Updated ut_run to be more reliable

---

source/core/coverage/ut_coverage.pkb

fixed issue when java source class may have similar name to PL/SQL package

Excluded java source from coverage

---

docs/about/CONTRIBUTING.md

Added detailed information about docker images and sqlcl.

Changes on CONTRIBUTING.MD

---

source/core/ut_suite_manager.pkb
tests/RunAll.sql
tests/ut_suite_manager/ut_suite_manager.CacheInvalidaesOnPackageDrop.sql

Fix cache invalidation on package drop
Addresses #267

fix cache invalidation on drop

---

docs/userguide/install.md
source/core/ut_suite_manager.pkb

Fixed issue, where suite_manager was throwing exception on call to `do_resolve` when package was visible but not executable.
Resolves #287

Fixed information on coverage privileges.

---

readme.md

Update of badges in readme.

---

docs/userguide/expectations.md
readme.md

Added reference on how to compare PLSQL records and collections with utPLSQL on 12c
Resolves #298

Updated readme.md

---

.travis/push_docs_to_gh_pages.sh
docs/index.md

- Fixed a bug in push_docs_to_gh_pages.sh
- Added reference to utPLSQL-demo-project in index.md

Fixed publishing documentation history.

---

docs/userguide/install.md
source/create_synonyms_and_grants_for_public.sql
source/create_synonyms_and_grants_for_user.sql
source/install.sql
source/readme.md

- Updated to install scripts to fail on bad schema_name
- Updated readme files to make it more explicit that SYSDBA access is needed for install

Fixes to install process

---

.travis/push_docs_to_gh_pages.sh

Fixed issue with gh-pages not getting updated when Travis build is executed from tag.
Resolves #320

Gh pages updated on TAG

---

develop/userguide/install.md
v3.0.0/userguide/install.md

A small fix in the documentation, changing the name of the download URL variables.

Download URL Variables

---

source/core/ut_annotations.pkb
tests/RunAll.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParseAnnotationParamsWithBrackets.sql
tests/ut_reporters/ut_documentation_reporter.providesCorrectLineFromStacktrace.sql

Fixed annotation parameter pattern matching

---

source/create_synonyms_and_grants_for_public.sql
source/create_synonyms_and_grants_for_user.sql

Fixed too early prompts in create synonym installation scripts

---

.travis.yml
source/core/coverage/ut_coverage.pkb
source/core/types/ut_run.tpb
source/core/ut_expectation_processor.pkb
source/core/ut_suite_manager.pkb
tests/RunAll.sql
tests/helpers/html_coverage_test.pck
tests/helpers/test_reporters_1.pkb
tests/ut_reporters/ut_html_reporter.UserOverrideSchemaCoverage.sql
tests/ut_suite_manager/ut_suite_manager.PackageWithDollarSign.sql
tests/ut_suite_manager/ut_suite_manager.PackageWithHash.sql
tests/ut_suite_manager/ut_suite_manager.TestWithDollarSign.sql
tests/ut_suite_manager/ut_suite_manager.TestWithHashSign.sql

Fixed dollar escape in procedure and user namess
changed ut3_user to ut3$user# (escaped variable in travis)
Fixes #331

Fixing $ and # sign in user and procedures

---

.travis.yml
.travis/build_release_archive.sh

- fixed #353 
- added .md5 files generation.
- added .md5 files upload with release
- fixed upload of archive files (was using bad/old names)

Release is now including md5 checksum for archives

---

docs/userguide/expectations.md
docs/userguide/getting-started.md

Here's a few more minor documentation fixes which I found today while reading expectations.md and getting-started.md.  I might add more later, but I noticed you're about to release v3.0.1 so thought I'd fire off the pull request before then.

A few more minor documentation fixes

---

docs/userguide/install.md

Resolves #360
Thanks to @pocelka for providing the content.

Install guide now provides snippet on how to download latest release on Windows

---

source/create_synonyms_and_grants_for_public.sql
source/create_synonyms_and_grants_for_user.sql
source/define_ut3_owner_param.sql
source/install.sql
source/install_component.sql
source/install_headless.sql
source/uninstall.sql

Install and Uninstall scripts are now much more readable

---

source/reporters/ut_xunit_reporter.tpb
tests/RunAll.sql
tests/ut_reporters/ut_xunit_reporter.ReportOnSuiteWithoutDesc.sql
tests/ut_reporters/ut_xunit_reporter.ReportOnTestWithoutDesc.sql

xUnit report test/suite name of description is null

---

.travis.yml

Use new image for 12c-r1

---

.travis.yml

decreesed image size by 200+ MB
added df -h so we can inspect changes in disk usage between builds

switch to docker image 12.2 version 4

---

source/install_headless.sql

fixed install_headless.sql

---

source/reporters/ut_documentation_reporter.tpb
tests/RunAll.sql
tests/ut_reporters/ut_documentation_reporter.reportTestTiming.sql

Added timing reporting for documentation reporter (nonconditional).
addressed #351

implemented timing reporting for documentation reporter

---

source/reporters/ut_documentation_reporter.tpb
tests/RunAll.sql
tests/ut_reporters/ut_documentation_reporter.reportMultipleWarnings.sql

Fixed indexing of warnings for documentation reporter

---

tests/lib/RunTest.sql

Improved reporting from RunTest

---

docs/userguide/coverage.md

Fixed documentation object names for file mappings

---

source/core/types/ut_expectation_result.tps

Fixed authid on `ut_expectation_result` to address #389

---

.travis/install.sh
source/core/coverage/proftab.sql
source/install.sql
source/install_headless.sql

Improved installation routine

---

source/core/ut_annotations.pkb
source/core/ut_suite_manager.pkb
tests/RunAll.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.spaceBeforeAnnotationParams.sql
tests/ut_suite_manager/ut_suite_manager.PackageWithDollarSign.sql
tests/ut_suite_manager/ut_suite_manager.PackageWithHash.sql
tests/ut_suite_manager/ut_suite_manager.TestWithDollarSign.sql
tests/ut_suite_manager/ut_suite_manager.TestWithHashSign.sql
tests/ut_suite_manager/ut_suite_manager.emptySuitePath.sql

Fix error with space before annotation params

---

docs/userguide/annotations.md

annotations.md

---

readme.md

Update readme.md - typo

---

source/reporters/ut_sonar_test_reporter.tpb
source/reporters/ut_sonar_test_reporter.tps
source/reporters/ut_teamcity_reporter.tpb
source/reporters/ut_teamcity_reporter_helper.pkb
source/reporters/ut_teamcity_reporter_helper.pks
tests/helpers/test_reporters.pks
tests/helpers/test_reporters_1.pks
tests/ut/ut.run.AcceptsSutePaths.sql
tests/ut/ut.run.WithGivenReporter.ExectutesAllInCurrentSchemaUsingReporter.sql
tests/ut/ut.run.function.AcceptsSutePaths.sql
tests/ut/ut.run.function.WithGivenReporter.ExectutesAllInCurrentSchemaUsingReporter.sql
tests/ut_reporters/ut_documentation_reporter.providesCorrectLineFromStacktrace.sql
tests/ut_reporters/ut_sonar_test_reporter.AcceptsFileMapping.sql
tests/ut_reporters/ut_sonar_test_reporter.ProducesExpectedOutputs.sql
tests/ut_reporters/ut_teamcity_reporter.ProducesExpectedOutputs.sql
tests/ut_reporters/ut_xunit_reporter.ProducesExpectedOutputs.sql

Resolves #413
@pazus, please verify the test for TeamCity test reporter as it seems to be giving suspicious outputs with suitepath too.
Do we need to fix this?

Fixed issue with Sonar Test reporter giving bad reports with suitepath.

---

source/core/types/ut_executable.tpb
source/core/types/ut_suite.tpb
source/core/types/ut_test.tpb
source/core/ut_utils.pkb
source/core/ut_utils.pks
tests/RunAll.sql
tests/ut_test/ut_test.ApplicationInfoOnExecution.sql

Implemented reporting to dbms_application_info

---

source/expectations/data_values/ut_data_value_refcursor.tpb
tests/RunAll.sql
tests/ut_expectations/ut.expect.to_equal.cursor.worksOnLargeDatasets.sql

Fixed a bug with comparison od ref_cursors with more than 1000 rows.

---

source/core/coverage/ut_coverage.pkb

Files that were not covered at all will not have coverage reported.
This feature addresses Sonar misbehaviour when consuming multiple coverage reports.

Changed the way coverage is gathered on project files.

---

source/core/ut_annotations.pks
tests/RunAll.sql
tests/ut_annotations/ut_annotations.parse_package_annotations.ParseProcedureAnnotationWithVeryLongName.sql

Fixes #459
Added additional test to prevent error in future

Increase allowed chars for annotation name to 250

---

.travis.yml

Also added the variable to the build

Implemented testing branch substitution

---

source/api/ut_runner.pkb
source/core/ut_expectation_processor.pkb
source/core/ut_metadata.pkb
source/core/ut_metadata.pks
test/install_tests.sql
test/ut_runner/test_ut_runner.pkb
test/ut_runner/test_ut_runner.pks

Fixed issues with self-testing.
Fixed issues with version compare for short version numbers.

Package body cache is now invalidated after every test run.

---

docs/userguide/expectations.md

Added example for custom expectation-fail message in docs

---

docs/about/project-details.md

Fixed link to contributing guide in the doc.

---

source/core/ut_utils.pkb
source/core/ut_utils.pks

Savepoint name is now generated from sys_guid.

---

docs/userguide/install.md

Updated privileges in doc

---

source/api/ut.pkb
source/api/ut_runner.pkb
source/api/ut_runner.pks
source/core/coverage/ut_coverage.pkb
test/ut_reporters/test_coverage.pkb
test/ut_reporters/test_coverage.pks
test/ut_reporters/test_coverage_sonar_reporter.pkb
test/ut_reporters/test_coveralls_reporter.pkb

Coverage can now be gathered with `a_include_objects` parameter
Resolves #511

Fixed coverage filtering issue.

---

source/core/ut_metadata.pkb
source/core/ut_metadata.pks
source/core/ut_suite_manager.pkb
test/ut_suite_manager/test_suite_manager.pkb

Simplified logic for building hirerachy of suites.
Logic separation so that suitepath deduplication is possible.

Refactoring of `ut_suite_manager`

---

development/refresh_sources.sh

Now refresh will use most recent cli release.

Fixed dev script to refresh of sources after `utPLSQL-cli` was released.

---

development/install.sh

The script will now stop on errors and make it easier to see where it failed.

Improved error reporting on `development/install.sh` script.

---

test/core/expectations/test_expect_not_to_be_null.pkb
test/core/expectations/test_expect_not_to_be_null.pks
test/helpers/expectations_helpers.pkb
test/helpers/expectations_helpers.pks
test/install_tests.sql

Implementation of the new design for expectations tests

New design for the expectations tests

---

test/core/expectations/test_expect_not_to_be_null.pkb
test/core/expectations/test_expect_not_to_be_null.pks

new tests for anydata in *not_to_be_null* expectation added

new tests for anydata added

---

source/expectations/data_values/ut_data_value_refcursor.tpb
test/core/expectations/test_expectations_cursor.pkb
test/core/expectations/test_expectations_cursor.pks

When a closed cursor is passed to expect, it throws a exception

---

source/core/ut_suite_manager.pkb

Deletion of duplicate check in *ut_suite_manager.pkb*

Deletion of duplicate check

---

source/api/ut_runner.pkb
test/core/reporters/test_coverage.pkb
test/core/reporters/test_coverage.pks

Coverage tmp table is now cleaned up after each run.
Resolves #562

Coverage tmp table is now cleaned up after each run.

---

source/core/ut_utils.pkb
source/core/ut_utils.pks
source/reporters/ut_xunit_reporter.tpb
test/core/reporters/test_xunit_reporter.pkb
test/core/reporters/test_xunit_reporter.pks

Resolves #572
Resolves utPLSQL/utPLSQL-cli#61

Fixed issue with NLS settings for decimal numbers in XML reporting.

---

source/core/types/ut_file_mapping.tpb

File mapping is now unique for individual object.

---

source/api/ut_runner.pkb
source/create_synonyms_and_grants_for_public.sql
source/create_synonyms_and_grants_for_user.sql

Added check for access to DBA/ALL views
Fixed missing grants for non-instantiable reporters causing reporters not to show on list of available reporters when DBA_TYPES view not accessible.

Fixed issue when user executing tests doesn't have access to DBA_TYPES view

---

source/core/ut_utils.pkb
source/core/ut_utils.pks
source/expectations/data_values/ut_compound_data_helper.pkb
source/expectations/data_values/ut_data_value_refcursor.tpb
test/core/expectations/compound_data/test_expectations_cursor.pkb
test/core/expectations/compound_data/test_expectations_cursor.pks

Changes to allow for comparing a implicit cursor

Fixed issue with implicit cursor

---

source/reporters/ut_junit_reporter.tpb
source/reporters/ut_sonar_test_reporter.tpb
source/reporters/ut_tfs_junit_reporter.tpb
test/core/reporters/test_junit_reporter.pkb
test/core/reporters/test_junit_reporter.pks
test/core/reporters/test_tfs_junit_reporter.pkb
test/core/reporters/test_tfs_junit_reporter.pks

Fix issue with CDDATA included in failure mesage.
Fixes #643

Fix issue where failure message includes special xml char like CDDATA etc.

---

docs/userguide/install.md

Fixed a gap in documentation - grants needed for DBMS_CRYPTO

---

.travis.yml
.travis/trigger_travis.sh

Fixes #501 
Added shell to trigger list of branches downstream.

Trigger subbuilds

---

source/check_object_grants.sql
source/check_sys_grants.sql
source/install.sql

Added scripts to validate privileges before install.

---

source/create_synonyms_and_grants_for_public.sql
source/create_user_grants.sql
source/create_user_synonyms.sql

Added grants and synonyms for `ut_expectation` and `ut_expectation_compound`

---

source/check_object_grants.sql

fix check_object_grants bug on all_tab_privs.

---

docs/userguide/annotations.md

Updated documentation.

---

source/core/ut_suite_builder.pkb
test/core/test_suite_builder.pkb
test/core/test_suite_builder.pks

Added reporting of warnings for unknown annotations.

---

.travis/download.sh
.travis/install_sqlcl.sh

Updated sqlcl version used for tests to version 18.2

Updated sqlcl version used for tests to version 18.2

---

source/core/coverage/proftab.sql
test/core/reporters/test_coverage/test_html_extended_reporter.pkb
test/core/reporters/test_extended_coverage.pkb

Extended the proftab column size for 12.2 long names

---

source/expectations/data_values/ut_compound_data_helper.pkb

Added cardinality to SQL on xmltable to avoid excessive estimates.

---

source/expectations/data_values/ut_compound_data_helper.pkb
source/expectations/data_values/ut_compound_data_value.tpb
test/core/expectations/test_expectations_cursor.pkb
test/core/expectations/test_expectations_cursor.pks

Due to missing duplicate_no in populated table the data results been skewed.
fixes #764

fix to unordered.

---

.travis/download.js
.travis/download.sh
.travis/install_sqlcl.sh

I had to add -L to curl parameters because Oracle now redirects the download url to https.

Fix sqlcl download

---

docs/userguide/reporters.md
docs/userguide/running-unit-tests.md

Updated documentation to include infrmation about reports encoding.

---

docs/userguide/expectations.md

Added description fo timestamp bind-variable comparison in cursor.

---

.travis/get_project_build_version.sh
.travis/get_project_version.sh
test/install_and_run_tests.sh

Changed `sed -r` to `sed -E`
Resolves #796

Removed unneeded `sed` from test-runner

---

source/api/ut_runner.pkb
source/api/ut_runner.pks
source/core/types/ut_reporter_info.tps
source/core/types/ut_reporters_info.tps
source/core/ut_utils.pkb
source/core/ut_utils.pks
source/install.sql
source/uninstall_objects.sql

by avoiding the costly and slow `connect by`
Resolves #814

Improved performance of `get_reporters_list`

---

docs/userguide/install.md
source/check_object_grants.sql
source/core/output_buffers/ut_output_table_buffer.tpb
source/create_utplsql_owner.sql
test/core/annotations/test_annotation_manager.pkb
test/core/test_ut_executable.pkb

Added support for `dbms_session.seep` on Oracle 18 and above

---

readme.md

The transparency we build by detailing the contributions is enough

Change disclaimer to be not overly defensive.

---

source/core/types/ut_suite_item.tpb
test/api/test_ut_run.pkb
test/api/test_ut_run.pks

Savepoints are working properly on distributed transactions.

---

docs/userguide/install.md
source/create_synonyms_and_grants_for_public.sql
source/create_user_grants.sql
source/create_user_synonyms.sql

Added grant and synonym for `ut_run_info`.
Resolves #822

Added `ut.version` and `ut_run_info()` onto documentation.

---

docs/userguide/annotations.md

Fixed example in documentation for context.

---

source/create_synonyms_and_grants_for_public.sql
source/create_user_grants.sql
source/create_user_synonyms.sql
test/core/min_grant_user/test_min_grant_user.pkb
test/core/min_grant_user/test_min_grant_user.pks
test/helpers/test_dummy_object.tps
test/helpers/test_dummy_object_list.tps
test/helpers/ut3user#.test_cursor_grants.pkb
test/helpers/ut3user#.test_cursor_grants.pks

Adding grants for public and create synonyms.
Adding extra tests.
Fixes #864

Fixing issue when users with min privs execute empty matcher.

---

source/expectations/data_values/ut_compound_data_helper.pkb

Fix #870 
Removing unnecessary exception handling.

Removing exception unnecessary

---

source/core/coverage/ut_coverage_helper.pkb
source/core/coverage/ut_coverage_sources_tmp.sql
source/core/output_buffers/ut_output_buffer_base.tpb
source/core/output_buffers/ut_output_buffer_base.tps
source/core/output_buffers/ut_output_buffer_info_tmp.sql
source/core/output_buffers/ut_output_buffer_tmp.sql
source/core/output_buffers/ut_output_clob_buffer_tmp.sql
source/core/output_buffers/ut_output_clob_table_buffer.tpb
source/core/output_buffers/ut_output_clob_table_buffer.tps
source/core/output_buffers/ut_output_table_buffer.tpb
source/core/output_buffers/ut_output_table_buffer.tps
source/install.sql
source/uninstall_objects.sql
test/ut3_tester/core/test_output_buffer.pkb
test/ut3_tester/core/test_output_buffer.pks

Fixed output_buffer purging error.

---

source/expectations/data_values/ut_compound_data_helper.pkb
source/expectations/data_values/ut_compound_data_helper.pks
source/expectations/data_values/ut_data_value_json.tpb

Fixes #947
Address issue for Oracle 11.2 where the local collection is used in SQL statement.

Fix issue for Oracle 11.2 where the local collection is used SQL

---

source/core/ut_suite_builder.pkb
test/ut3_tester/core/test_suite_builder.pkb

Added `package` to annotation warnings.

---

source/core/ut_suite_cache_manager.pkb
test/ut3_tester_helper/run_helper.pkb
test/ut3_user/api/test_ut_runner.pkb

Fixed issue with get_Cached_suite_rows syntax.

---

.travis/download.js
.travis/download.sh
source/core/ut_utils.pkb

Resolve security issues around insecure username for utplsql owner

---

.gitattributes

According to https://apextips.blogspot.com/2019/09/correctly-classifying-plsql-source-code.html

Update .gitattributes - add “*.sql linguist-language=PLSQL”

---

test/ut3_tester_helper/coverage_helper.pkb

Fixed test dependency.

---

source/core/ut_expectation_processor.pkb
test/ut3_tester/core/expectations/test_expectation_processor.pkb
test/ut3_tester/core/expectations/test_expectation_processor.pks

Fixed issue with stack parsing on Windows install of utPLSQL

---

.travis.yml

Fix Travis CI problem with missing java9 package

---

.travis.yml
docs/userguide/annotations.md
docs/userguide/running-unit-tests.md
source/core/ut_suite_builder.pkb
source/core/ut_suite_cache_manager.pkb
test/ut3_tester/core/test_suite_builder.pkb
test/ut3_tester/core/test_suite_builder.pks
test/ut3_user/api/test_ut_run.pkb
test/ut3_user/api/test_ut_run.pks

Added ability to exclude items by tags.

---

readme.md

To indicate total number of downloads for the project

Added downloads badge

---

docs/userguide/expectations.md
test/ut3_user/expectations/test_expectations_cursor.pkb
test/ut3_user/expectations/test_expectations_cursor.pks

Updated tests o represent the issue more clearly.
Closes #880

Updated documentation for whitespace vs null compare.

---

source/core/ut_suite_cache_manager.pkb
test/ut3_tester/core/test_suite_builder.pkb
test/ut3_tester/core/test_suite_builder.pks

Changed ordering of tests for suites with context

---

source/reporters/ut_teamcity_reporter.tpb
test/ut3_user/reporters/test_teamcity_reporter.pkb

Fixed Teamcity reporting of errors

---

test/ut3_user/expectations/test_expectations_cursor.pkb

Fixed flaky tests that can fail on occasion when a second flips during test execution.

Fixed flaky tests

---

docs/userguide/install.md

Restructuring utPSLQL install guide.

---

.github/ISSUE_TEMPLATE/feature_request.md
docs/about/project-details.md
docs/about/support.md
docs/userguide/install.md
readme.md

Resolves #1064
updated invite link for slack as the herokuapp invite solution doesn't since quite some time and Slack has it's own invite links now.

Added explicit requirements

---

.travis/install.sh
source/reporters/ut_realtime_reporter.tpb
test/ut3_user/reporters/test_realtime_reporter.pkb
test/ut3_user/reporters/test_realtime_reporter.pks

Fix invalid XML message with nested CDATA section causes in ut_realtime_reporter

---

source/core/annotations/ut_annotation_manager.pkb
test/ut3_tester_helper/annotation_cache_helper.pkb

Fixes to DDL Trigger annotation parsing on 11g

---

test/ut3_user/reporters/test_coverage/test_cov_cobertura_reporter.pkb
test/ut3_user/reporters/test_coverage/test_coverage_standalone.pkb
test/ut3_user/reporters/test_coverage/test_proftab_coverage.pkb

Updated unit tests after coverage format fix by @OsBlaineOra in: #1137

Updated unit tests after coverage format fix

---

source/install.sql

Removed duplicate profiler table installation.

---

docs/userguide/advanced_data_comparison.md

Typo (is -> if). This way the sentence makes some sense to me. Hope I got it right.

Fix typo in advanced_data_comparison.md

---

.github/workflows/build.yml
sonar-project.properties

Testing to see if we can get multiple sonar analysis results in a PR (one per each job run).
> Running parallel Sonar analysis is not possible.
Added CodeCov coverage analysis on project.
Added DB level object analysis with sonar.

Improvements in project build coverage reporting.

---

.github/workflows/release.yml

Between each job looks like all settings and env needs to be set again.
Closes #1190 1190

The env are not set for archives files.

---

.github/scripts/validate_report_files.sh
.github/workflows/build.yml

Resolves instability and slowness of HTML validation with `https://validator.w3.org/` validator

Run html validator as a local container on GithubActions

---

source/uninstall_objects.sql

Fixing problem with uninstall script buffer overflow on DBMS_OUTPUT.
Resolves: #1220

Fix uninstall scripts

---

source/uninstall_synonyms.sql

The counter should not be incremented when an exception occurs.

Fix dropped synonyms counter.

---

source/core/coverage/ut_coverage.pkb
source/core/ut_suite_manager.pkb
source/core/ut_suite_manager.pks
test/ut3_tester_helper/coverage_helper.pkb
test/ut3_tester_helper/run_helper.pkb
test/ut3_user/reporters/test_coverage/test_extended_coverage.pkb
test/ut3_user/reporters/test_coverage/test_proftab_coverage.pkb

Exclude Unit Test packages from coverage

---

source/expectations/data_values/ut_cursor_details.tpb
test/ut3_user/expectations/test_expectation_anydata.pkb
test/ut3_user/expectations/test_expectation_anydata.pks

Added support for long type names in tests.

---

docs/userguide/running-unit-tests.md

Just stumbled across a duplicate in Your (excellent!!) documentation. I think it can be removed. Thanks for utplsql <3

fix(doc): Update running-unit-tests.md - remove example

---

docs/userguide/best-practices.md

Fixes #1273
Replaced 3-spaces indentation with 4-spaces indentation to fix nested list issue

Fix nested list issue in docs
